config/routes.rb
Rails.application.routes.draw do
  root 'votes#index'
  resources :votes, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  def self.totals
    [Vote.where(color: 'red').count, Vote.where(color: 'blue').count]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def index
    @votes = Vote.totals

    respond_to do |format|
      format.html
      format.json { render json: @votes }
    end
  end

  def create
    Vote.create(vote_params)
    @votes = Vote.totals
    respond_to do |format|
      format.js
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiveDataRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/votes/create.js.erb
$("#red-count").html("<%= @votes[0] %>");
$("#blue-count").html("<%= @votes[1] %>");

app/views/votes/index.html.erb
<div class="main-container">
  <h1>Vote for best color.</h1>

  <div id="vote-counter">
    <h3>Choose!</h3>
    <p>Red Team: <span id="red-count"><%= @votes[0] %></span></p>
    <p>Blue Team: <span id="blue-count"><%= @votes[1] %></span></p>
  </div>

  <div id="voting-box">
    <%= link_to 'Vote Red', votes_path(vote: {color: 'red'}), {remote: true, method: :post, class: 'vote-button red' } %>
    <%= link_to 'Vote Blue', votes_path(vote: {color: 'blue'}), {remote: true, method: :post, class: 'vote-button blue' } %>
  </div>
</div>

<div id="plot-container">
  <svg id="plot"></svg>
</div>